/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData money_1 = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dollar = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData credit_card = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData briefcase = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData credit_card_1 = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData money = IconData(0xf0d6, fontFamily: _kFontFam);
  static const IconData paypal = IconData(0xf1ed, fontFamily: _kFontFam);
  static const IconData cc_mastercard = IconData(0xf1f1, fontFamily: _kFontFam);
  static const IconData cc_paypal = IconData(0xf1f4, fontFamily: _kFontFam);
  static const IconData cc_stripe = IconData(0xf1f5, fontFamily: _kFontFam);
  static const IconData credit_card_alt =
      IconData(0xf283, fontFamily: _kFontFam);
}
